# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Get your daily GitHub star recommendation
email:
description: > # this means to ignore newlines until "baseurl:"
  Get your daily GitHub star recommendation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rollbrettler.github.io/daily-stars" # the base hostname & protocol for your site
github_username:  rollbrettler

# Build settings
markdown: kramdown
